server:
  port: 8081
  servlet:
    context-path: /product

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/products_microservice"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true